### PR TITLE
解决Issue 112

### PR DESCRIPTION
**Pull request by liuzilong66666**
### Which changes (Bug/Feature):

Fixes #

### Special notes for reviewers:

```
none
```

### CODE REVIEW

**Review by colynn — COMMENTED** [review]
based on `v1.5.0-feat-app-refactor` branch please

**Comment by colynn** [comment]
@liuzilong66666 新增接口的用途及返回  请说明，

修改后的界面请附图

**Comment by fanhousanbu** [comment]
> ### Which changes (Bug/Feature):
> Fixes #112 

@liuzilong66666

**Comment by colynn** [comment]
transfer to #122

**Pull request closed without merging**
